spring:
  application:
    name: api

  datasource:
    url: jdbc:postgresql://localhost:5432/ibmbank_api
    username: postgres
    password: Th@bata2012
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    show-sql: true
